import re

def build_reporter():
    with open('css_saved.txt', 'r', encoding='utf-8') as f:
        css = f.read()

    with open('script_saved.txt', 'r', encoding='utf-8') as f:
        script = f.read()

    with open('body_saved.html', 'r', encoding='utf-8') as f:
        body = f.read()

    # We need to make script dynamic.
    # chart-revenue-expense series 0 data: income
    # chart-revenue-expense series 1 data: expense
    script = re.sub(r"\{name:'计奖收入',type:'line',data:\[[0-9,]+\]", "{name:'计奖收入',type:'line',data:[${revData.join(',')}]", script)
    script = re.sub(r"\{name:'科室支出',type:'line',data:\[[0-9,]+\]", "{name:'科室支出',type:'line',data:[${expData.join(',')}]", script)
    
    # chart-expense-composition data
    script = re.sub(r'data:\[\{"name":"各类消耗"[^\]]+\]', 'data:${JSON.stringify(expensePieData)}', script)
    
    # chart-workload data
    script = re.sub(r"\{type:'bar',barWidth:'50%',data:\[.*?\]", "{type:'bar',barWidth:'50%',data:${JSON.stringify(workloadData)}", script)
    
    # chart-gauge data
    script = re.sub(r"data:\[\{value:0,name:'支收比'\}\]", "data:[{value:${costRatioPct},name:'支收比'}]", script)
    
    # chart-procurement-top data & yaxis
    script = re.sub(r'yAxis:\{type:\'category\',data:\[.*?\],inverse', 'yAxis:{type:\'category\',data:${JSON.stringify(procYData)},inverse', script)
    script = re.sub(r"series:\[\{type:'bar',barWidth:'60%',data:\[.*?\]", "series:[{type:'bar',barWidth:'60%',data:${JSON.stringify(procSData)}", script)

    # chart-supplier data
    script = re.sub(r'data:\[\{"name":"海安康健[^\]]+\]', 'data:${JSON.stringify(suppPieData)}', script)

    # Create the JS wrapper for script
    chart_script_fn = """
function chartScripts(analysis) {
  const meta = analysis.meta || {};
  const month = meta.month || 1;
  const revItems = analysis.revenue || {items:[]};
  const expItems = analysis.expenses || {items:[]};
  const workTrend = analysis.workload?.trend || {};
  
  const srTot = revItems.items.find(i => i.id === 'revenue_total') || {monthly:[]};
  const seTot = expItems.items.find(i => i.id === 'expense_total') || {monthly:[]};
  
  const revData = Array.from({length:12}, (_, i) => srTot.monthly[i+1] || 0);
  const expData = Array.from({length:12}, (_, i) => seTot.monthly[i+1] || 0);
  
  const ef = analysis.efficiency || {};
  const costRatioPct = ef.cost_revenue_ratio != null ? Math.min((ef.cost_revenue_ratio*100).toFixed(1), 100) : 0;
  
  const expGroups = analysis.expenseGroups || [];
  const expensePieData = expGroups.filter(g => g.value > 0).map(g => ({name: g.name, value: g.value}));
  
  const wlData = Array.from({length:12}, (_, i) => {
    let v = workTrend[i+1] || 0;
    return {value: v, itemStyle: {color: (i+1)===month ? '#2563eb' : '#93c5fd', borderRadius: [4,4,0,0]}};
  });
  const workloadData = wlData;
  
  const procs = analysis.procurement?.items || [];
  const top10 = [...procs].sort((a,b)=>b.amount-a.amount).slice(0,10);
  const procYData = top10.map(p => p.item_name);
  const procSData = top10.map(p => ({value: p.amount, itemStyle: {borderRadius: [0,4,4,0]}}));
  
  const supps = analysis.procurement?.suppliers || [];
  const suppPieData = supps.slice(0, 10).map(s => ({name: s.supplier, value: s.amount}));

  return `
<script>
${script}
</script>
  `;
}
"""

    # We will just write a new reporter.js from scratch, and dynamically render parts
    # So we don't need the hardcoded body from body_saved.html unless we use it as a shell
    # Since writing a giant regex for body is too hard, let's just write the structured JS template literals directly using python multi-line strings!

    out_js = f"""
// Auto-generated by Antigravity
const ML = ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'];

function fmtMoney(num) {{ return num == null ? '--' : num.toLocaleString('zh-CN', {{ style: 'currency', currency: 'CNY' }}); }}
function fmtNum(num) {{ return num == null ? '--' : num.toLocaleString('zh-CN'); }}
function fmtChange(num) {{ if (num == null) return '--'; return (num > 0 ? '+' : '') + (num * 100).toFixed(1) + '%'; }}
function fmtPct(num) {{ return num == null ? '--' : (num * 100).toFixed(1) + '%'; }}
function esc(str) {{ return (str || '').replace(/[&<>'"]/g, c => ({{ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }})[c]); }}

function changeClass(val, invert = false) {{
  if (val == null || val === 0) return '';
  const positive = val > 0;
  const good = invert ? !positive : positive;
  return good ? 'val-pos' : 'val-neg';
}}

function getActiveMonths(trendObj) {{
  if (!trendObj) return [];
  return Object.keys(trendObj).map(Number).sort((a, b) => a - b).filter(m => trendObj[m] != null);
}}

function reportCSS() {{
  return `<style>{css}</style>`;
}}

{chart_script_fn}

// Now we need the main report body. We will construct it piecemeal to match the new UI.
// Due to size limits, we will read the user's `templates/病理科...html` body and do replacements!
"""
    with open('src/reporter.js', 'w', encoding='utf-8') as f:
        f.write(out_js)

build_reporter()
